#! /usr/bin/perl -pi

#******************************************************************************
#
#  An index file looks like:
#
#        nnnnnnnnnnMSH...nnnnnnnnnnMSH...nnnnnnnnnnMSH...nnnnnnnnnnMSH...
#
#  This script will convert it to:
#
#        MSH...
#        MSH...
#        MSH...
#        MSH...
#
#   NOTE:  The original files are replaced with the new one!!!! NO BACKUPS!
#
#******************************************************************************

s/$/\n/;                   # Add a newline at the end
s/^[0-9]{10}//;      # Dont add a newline on the first message
s/[0-9]{10}/\n/g;   # Add a newline between the messages


